In [1]:
import numpy as np

#  The Basics

In [4]:
a = np.array([1,2,4,5], dtype='int16')

In [18]:
# getting dimensions
a.ndim

4

In [9]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# getting shape
print(b.shape)

# getting number of rows 
print(b.shape[0])

# getting number of columns
b.shape[1]

(2, 3)
2


3

In [12]:
# getting type
b.dtype

dtype('int32')

In [20]:
# getting each itemsize
# 4 bytes for an int
# 8 bytes for a float
print(b.itemsize)

# getting total number of elements
b.size

4


6

In [21]:
# getting total size
b.nbytes
# or 
b.itemsize * b.size

24

# Accessing, Changing specific elements, rows and colums etc.

In [22]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
# getting a specific element [r,c]
c[1,2]

10

In [28]:
# getting a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# getting a specific column
c[:,1]

array([2, 9])

In [31]:
# getting a little more fancy [start:stop:step]
c[0, 1:6:2]

array([2, 4, 6])

In [36]:
# changing specific elements
c[1,2] = 55
c

array([[  1,   2, 100,   4,   5,   6,   7],
       [  8,   9,  55,  11,  12,  13,  14]])

In [38]:
# changing specific rows or columns
c[:, 2] = 100
# or
c[:, 3] = [100,100]
c

array([[  1,   2, 100, 100,   5,   6,   7],
       [  8,   9, 100, 100,  12,  13,  14]])